- defaults:
    link:
      if: '[ "$(uname)" == "Linux" ]'
      create: true
      force: true
      relink: true

- clean: ['~']

- link:
    ~/.bash_logout:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.gitattributes:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.shell:
    ~/.vimrc:
    ~/.config/Code/User/settings.json:
      path: vscode/settings.json

- shell:
  -
    command: bash shell/msys.sh
    stderr: true
    stdout: true