- defaults:
    link:
      create: true
      force: true
      relink: true

- clean: ['~']

- link:
    ~/.shell:
    ~/.bash_logout:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.editorconfig:
    ~/.gitattributes:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.vimrc:
    ~/.config/Code/User/settings.json: vscode/settings.json
    ~/.config/flake8: flake8

- shell:
  -
    command: bash shell/msys.sh
    stderr: true
    stdout: true
