- defaults:
    link:
      create: true
      force: true
      relink: true
    shell:
      stderr: true
      stdout: true

- clean: ["~"]

- link:
    ~/.shell:
    ~/.bash_logout:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.editorconfig:
    ~/.gitattributes: git/gitattributes
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global
    ~/.config/Code/User/settings.json: vscode/settings.json
    ~/.config/flake8: flake8

- if:
    cond: echo "$OSTYPE" | grep msys
    met:
      - link:
          ~/.minttyrc:
      - shell:
          - command: bash shell/msys.sh

- if:
    cond: test "$REMOTE_CONTAINERS" != true
    met:
      - create:
          - ~/git/cal-itp
          - ~/git/compiler
          - ~/git/thekaveman
      - link:
          ~/git/thekaveman/.gitconfig: git/thekaveman.gitconfig
          ~/.vimrc:
      - if:
          cond: echo "$OSTYPE" | grep linux
          met:
            - if:
                cond: python --version
                unmet:
                  - shell:
                      - command: bash shell/python.sh
            - if:
                cond: docker --version
                unmet:
                  - shell:
                      - command: bash shell/docker.sh
            - if:
                cond: dotnet --version
                unmet:
                  - shell:
                      - command: bash shell/dotnet.sh
            - if:
                cond: terraform --version
                unmet:
                  - shell:
                      - command: bash shell/terraform.sh
      - if:
          cond: echo "$OSTYPE" | grep darwin
          met:
            - if:
                cond: brew --version
                unmet:
                  - shell:
                      - command: bash brew/install.sh
            - if:
                cond: python3 --version
                unmet:
                  - shell:
                      - command: bash brew/python.sh
            - if:
                cond: docker --version
                unmet:
                  - link:
                      ~/.docker/config.json: docker/config.osx.json
                  - shell:
                      - command: bash brew/docker.sh
            - if:
                cond: gcloud --version
                unmet:
                  - shell:
                      - command: bash brew/google.sh

- if:
    cond: code -v
    met:
      - shell:
          - command: bash vscode/install-extensions.sh
