- defaults:
    link:
      create: true
      force: true
      relink: true

- clean: ['~']

- link:
    ~/.bash_logout:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.gitattributes:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.shell:
    ~/.vimrc:
    ~/.config/Code/User/settings.json:
      if: '[["$OSTYPE" != "msys" && "$OSTYPE" != "cygwin"]]'
      source: vscode/settings.json
    ~/AppData/Roaming/Code/User/settings.json:
      source: vscode/settings.json
      if: '[["$OSTYPE" == "msys" || "$OSTYPE" == "cygwin"]]'