- defaults:
    link:
      create: true
      force: true
      relink: true

- clean: ['~']

- link:
    ~/.bash_logout:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.gitattributes:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.shell:
    ~/.vimrc: