- defaults:
    link:
      create: true
      force: true
      relink: true
    shell:
      stderr: true
      stdout: true

- clean: ["~"]

- link:
    ~/.shell:
    ~/.bash_logout:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.editorconfig:
    ~/.gitattributes: git/gitattributes
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global
    ~/.config/flake8: flake8

- if:
    cond: echo "$OSTYPE" | grep msys
    met:
      - link:
          ~/.minttyrc:
      - shell:
          - command: bash shell/msys.sh

- if:
    cond: test "$REMOTE_CONTAINERS" != true
    met:
      - create:
          - ~/git/cal-itp
          - ~/git/compiler
          - ~/git/thekaveman
      - link:
          ~/git/thekaveman/.gitconfig: git/thekaveman.gitconfig
          ~/.vimrc:
      - if:
          cond: echo "$OSTYPE" | grep linux
          met:
            - shell:
                - command: bash tools/linux-prereq.sh
      - if:
          cond: brew --version
          unmet:
            - shell:
                - command: bash tools/brew.sh
      - if:
          cond: python --version || python3 --version
          unmet:
            - shell:
                - command: bash tools/python.sh
      - if:
          cond: docker --version
          unmet:
            - shell:
                - command: bash tools/docker.sh
            - if:
                cond: echo "$OSTYPE" | grep darwin
                met:
                  - shell:
                      - command: mkdir -p ~/.docker
                  - link:
                      ~/.docker/config.json: docker/config.osx.json
      - if:
          cond: aws --version
          unmet:
            - shell:
                - command: bash tools/aws.sh
      - if:
          cond: az version
          unmet:
            - shell:
                - command: bash tools/azure.sh
      - if:
          cond: dotnet --version
          unmet:
            - shell:
                - command: bash tools/dotnet.sh
      - if:
          cond: gcloud --version
          unmet:
            - shell:
                - command: bash tools/gcloud.sh
      - if:
          cond: terraform --version
          unmet:
            - shell:
                - command: bash tools/terraform.sh
      - if:
          cond: code -v
          unmet:
            - shell:
                - command: bash tools/vscode.sh

- if:
    cond: echo "$OSTYPE" | grep linux
    met:
      - link:
          ~/.config/Code/User/settings.json: vscode/settings.json
- if:
    cond: echo "$OSTYPE" | grep darwin
    met:
      - link:
          "~/Library/Application Support/Code/User/settings.json": vscode/settings.json

- if:
    cond: code -v
    met:
      - shell:
          - command: bash vscode/install-extensions.sh
