- defaults:
    link:
      create: true
      force: true
      relink: true

- clean: ["~"]

- create:
    - ~/git/cal-itp
    - ~/git/compiler
    - ~/git/thekaveman

- link:
    ~/.shell:
    ~/.bash_logout:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.editorconfig:
    ~/.gitattributes:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.minttyrc:
    ~/.vimrc:
    ~/.config/Code/User/settings.json: vscode/settings.json
    ~/.config/flake8: flake8

- shell:
    - command: bash shell/msys.sh
      stderr: true
      stdout: true

    - command: bash vscode/install-extensions.sh
      stderr: true
      stdout: true
