- defaults:
    link:
      create: true
      force: true
      relink: true
    shell:
      stderr: true
      stdout: true

- clean: ["~"]

- create:
    - ~/git/cal-itp
    - ~/git/compiler
    - ~/git/thekaveman

- link:
    ~/.shell:
    ~/.bash_logout:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.editorconfig:
    ~/.gitattributes: git/gitattributes
    ~/.gitconfig: git/gitconfig
    ~/git/thekaveman/.gitconfig: git/thekaveman.gitconfig
    ~/.gitignore_global: git/gitignore_global
    ~/.minttyrc:
    ~/.vimrc:
    ~/.config/Code/User/settings.json: vscode/settings.json
    ~/.config/flake8: flake8

- if:
    cond: echo "$OSTYPE" | grep msys
    met:
      - shell:
          - command: bash shell/msys.sh
            stderr: true
            stdout: true

- if:
    cond: echo "$OSTYPE" | grep linux && test "$REMOTE_CONTAINERS" != true && ! python --version
    met:
      - shell:
          - command: bash shell/python.sh
            stderr: true
            stdout: true

- if:
    cond: echo "$OSTYPE" | grep linux && test "$REMOTE_CONTAINERS" != true && ! docker --version
    met:
      - shell:
          - command: bash shell/docker.sh
            stderr: true
            stdout: true

- if:
    cond: echo "$OSTYPE" | grep linux && test "$REMOTE_CONTAINERS" != true && ! dotnet --version
    met:
      - shell:
          - command: bash shell/dotnet.sh
            stderr: true
            stdout: true

- if:
    cond: echo "$OSTYPE" | grep linux && test "$REMOTE_CONTAINERS" != true && ! terraform --version
    met:
      - shell:
          - command: bash shell/terraform.sh
            stderr: true
            stdout: true

- if:
    cond: code -v
    met:
      - shell:
          - command: bash vscode/install-extensions.sh
            stderr: true
            stdout: true
