- defaults:
    link:
      create: true
      force: true
      relink: true
    shell:
      stderr: true
      stdout: true

- clean: ["~"]

- link:
    ~/.shell:
    ~/.bash_logout:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.editorconfig:
    ~/.gitattributes: git/gitattributes
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global
    ~/.config/flake8: flake8

- if:
    cond: echo "$OSTYPE" | grep msys
    met:
      - link:
          ~/.minttyrc:
      - shell:
          - command: bash shell/msys.sh

- if:
    cond: test "$REMOTE_CONTAINERS" != true
    met:
      - create:
          - ~/git/cal-itp
          - ~/git/compiler
          - ~/git/thekaveman
      - link:
          ~/git/thekaveman/.gitconfig: git/thekaveman.gitconfig
          ~/.vimrc:
      - if:
          cond: brew --version
          unmet:
            - shell:
                - command: bash shell/brew.sh
      - if:
          cond: python --version || python3 --version
          unmet:
            - shell:
                - command: bash shell/python.sh
      - if:
          cond: docker --version
          unmet:
            - shell:
                - command: bash shell/docker.sh
            - if:
                cond: echo "$OSTYPE" | grep darwin
                met:
                  - shell:
                      - command: mkdir -p ~/.docker
                  - link:
                      ~/.docker/config.json: docker/config.osx.json
      - if:
          cond: gcloud --version
          unmet:
            - shell:
                - command: bash brew/google.sh
      - if:
          cond: dotnet --version
          unmet:
            - shell:
                - command: bash shell/dotnet.sh
      - if:
          cond: gcloud --version
          unmet:
            - shell:
                - command: bash shell/google.sh
      - if:
          cond: terraform --version
          unmet:
            - shell:
                - command: bash shell/terraform.sh
      - if:
          cond: code -v
          unmet:
            - shell:
                - command: bash shell/vscode.sh

- if:
    cond: code -v
    met:
      - if:
          cond: echo "$OSTYPE" | grep linux
          met:
            - link:
                ~/.config/Code/User/settings.json: vscode/settings.json
      - if:
          cond: echo "$OSTYPE" | grep darwin
          met:
            - link:
                "~/Library/Application Support/Code/User/settings.json": vscode/settings.json
      - shell:
          - command: bash vscode/install-extensions.sh
